# Generated by Django 3.2.9 on 2021-11-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(verbose_name='Вариант ответа'),
        ),
    ]
